### ISSUE TITLE
Nothing to generate

### ISSUE THREAD

**Issue by Jakeai94** [XavierXiao/Dreambooth-Stable-Diffusion#126]
Sorry im very new to this, I have followed steps according to youtube tutorials 
when i click train this is what comes up, what do i do from here?

Model dir set to: D:\StableDiffusionAi\stable-diffusion-webui\models\dreambooth\Protogen2LukeH
Model dir set to: D:\StableDiffusionAi\stable-diffusion-webui\models\dreambooth\Protogen2LukeH
Initializing dreambooth training...
Pre-processing images: Reference faces: : 0it [00:00, ?it/s]
Nothing to generate.
Traceback (most recent call last):
  File "D:\StableDiffusionAi\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 681, in start_training
    result = main(use_txt2img=use_txt2img)
  File "D:\StableDiffusionAi\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1148, in main
    return inner_loop()
  File "D:\StableDiffusionAi\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\StableDiffusionAi\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 226, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "D:\StableDiffusionAi\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 598, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\StableDiffusionAi\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 442, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\StableDiffusionAi\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\StableDiffusionAi\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\StableDiffusionAi\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\StableDiffusionAi\stable-diffusion-webui\models\dreambooth\Protogen2LukeH\working\tokenizer'.
Restored system models.

**Comment by Webtransformer** [comment]
I have a similar problem.
