### ISSUE TITLE
install error, log blow

### ISSUE THREAD

**Issue by adhhrg** [XavierXiao/Dreambooth-Stable-Diffusion#127]
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: bff61c6b92b79ece2e140ee240e0628dd9a4ebef
SD-WebUI revision:

Checking Dreambooth requirements...
Failed to install Dreambooth requirements.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[!] accelerate version 0.12.0 installed.
[!] bitsandbytes NOT installed.
[!] diffusers NOT installed.
[!] transformers version 4.25.1 installed.
[!] xformers NOT installed.
Launch errors detected: ['Incorrect version of accelerate installed.', 'bitsandbytes not installed.', 'diffusers not installed.', 'Incorrect version of transformers installed.', 'xformers not installed.']

#######################################################################################################

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Script path is D:\ai\stable-diffusion-webui
Error loading script: api.py
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 11, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils.image_utils import get_scheduler_names
  File "D:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "D:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 14, in <module>
    from dreambooth.dreambooth import shared  # noqa
ModuleNotFoundError: No module named 'dreambooth.dreambooth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 37, in <module>
    from dreambooth.dreambooth import shared  # noqa
ModuleNotFoundError: No module named 'dreambooth.dreambooth'

**Comment by Xoiron** [comment]
I'm having the same issue as well. Still troubleshooting what exactly is going on. even added the arg --xformers to see if this changed anything. Nothing yet so far.
