### ISSUE TITLE
AttributeError: 'CLIPTextEmbeddings' object has no attribute 'embedding_forward', help!

### ISSUE THREAD

**Issue by friendmine** [XavierXiao/Dreambooth-Stable-Diffusion#130]
I got the erros
LatentDiffusion: Also optimizing conditioner params!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zyd/miniconda3/envs/diffuser/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/zyd/miniconda3/envs/diffuser/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/zyd/miniconda3/envs/diffuser/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CLIPTextEmbeddings' object has no attribute 'embedding_forward'

**Comment by lostnull** [comment]
Got the same error, were you able to solve this?

**Comment by zhengkw18** [comment]
Same error, can anyone solve this?

**Comment by HoJ-Onle** [comment]
I got the same error, have you solved this problem?

**Comment by bhosalems** [comment]
Similar error any further updates ?
