### ISSUE TITLE
"AssertionError: Only .pt files are supported" when trying to create additional class images.

### ISSUE THREAD

**Issue by Sur3** [XavierXiao/Dreambooth-Stable-Diffusion#135]
Hi I started training a LoRA and I want to increase the number of class images, but I always get the following error when trying to generate additional class images:

```
Generating class images 0/942::   0%|                                                       | 0/942 [00:00<?, ?it/s]Using scheduler: DDIM
Traceback (most recent call last):
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 230, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 120, in generate_classifiers
    builder = ImageBuilder(
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 136, in __init__
    lora_txt_path = _text_lora_path_ui(lora_model_path)
  File "/home/user/system/stable-diffusion-webui/extensions/sd_dreambooth_extension/lora_diffusion/lora.py", line 844, in _text_lora_path_ui
    assert path.endswith(".pt"), "Only .pt files are supported"
AssertionError: Only .pt files are supported
```

**Comment by Sur3** [comment]
Closing because I seem to have posted in the wrong repo.
