### ISSUE TITLE
Running gives unexpected keyword argument 'personalization_config'

### ISSUE THREAD

**Issue by atomical** [XavierXiao/Dreambooth-Stable-Diffusion#17]
```
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 292, in <module>
    main()
  File "scripts/stable_txt2img.py", line 195, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/stable_txt2img.py", line 31, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/Users/adam/workspace/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/Users/adam/workspace/stable-diffusion/ldm/models/diffusion/ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'personalization_config'
```

**Comment by atomical** [comment]
Recreated env and that solved this problem.

**Comment by 523997931** [comment]
> Recreated env and that solved this problem.

hello, I meet the same question, do you remember how to recreated the env to solve the problem?
