### ISSUE TITLE
DreamBooth Stable Diffusion training now possible in 10 GB VRAM, and it runs about 2 times faster.

### ISSUE THREAD

**Issue by ShivamShrirao** [XavierXiao/Dreambooth-Stable-Diffusion#35]
Hey, So I managed to run Stable Diffusion dreambooth training in just 17.7GB GPU usage by replacing the attention with memory efficient flash attention from [xformers](https://github.com/facebookresearch/xformers). Along with using way less memory, it also runs 2 times faster. So it's possible to train SD in 24GB GPUs now. Tested on Nvidia A10G, took 15-20 mins to train. I hope it's helpful.

Code in my fork: https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/

![Screenshot_20220927_042425](https://user-images.githubusercontent.com/37087513/192394776-17dde282-4e5a-48b5-8ed4-28ec3e98b985.png)

### Can even train on batch size of 2.

![Screenshot_20220927_042648](https://user-images.githubusercontent.com/37087513/192395033-e364cb60-f569-4843-931b-72a6d9aa85e3.png)

With some more tweaks it might be possible to train even on 16 GB gpus.

And it works, Outputs: Me in Fortnite
![Me in Fortnite](https://user-images.githubusercontent.com/37087513/192395417-f3651fcd-579c-44de-9efa-3fdc409caf51.jpg)

https://github.com/huggingface/diffusers/pull/554#issuecomment-1258751183

**Comment by TemporalLabsLLC-SOL** [comment]
Very cool. Doing what I can for 16gb too.

**Comment by TemporalLabsLLC-SOL** [comment]
I'm running into issues with it finding the gpus I think. 4xA10G. I'll post code tomorrow.

**Comment by ShivamShrirao** [comment]
Wow, Using the 8bit adam optimizer from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) along with [xformers](https://github.com/facebookresearch/xformers) reduces the memory usage to 12.5 GB.
Colab: https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb
![Screenshot_20220927_213651](https://user-images.githubusercontent.com/37087513/192585069-93dd3686-b28d-49c0-a5d2-edf29c317c78.png)
Code: https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/
![Screenshot_20220927_185927](https://user-images.githubusercontent.com/37087513/192539750-2e14d492-2e81-44a6-9889-b82e190ac4bd.png)

**Comment by Daniel-Kelvich** [comment]
There is no such file.
404 Client Error: Entry Not Found for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/main/config.json

Edit: Issue resolved.

**Comment by Mistborn-First-Era** [comment]
Do you have a donation link? I don't have much, but you are doing great work.

**Comment by ShivamShrirao** [comment]
> Do you have a donation link? I don't have much, but you are doing great work.

Hey, Thanks. No donation link haha. Good to hear you liked it. It has been quite fun to do for me.

**Comment by pdjohntony** [comment]
@ShivamShrirao I've been trying to run your notebook on Runpod with Pytorch and an A5000 but I'm getting an error during pip install "Building wheel for xformers (setup.py) ... error".
Training starts with a bitsandbytes bug report but runs and eventually after 20 min of training it crashes.

I'd also love to donate if I can get this working.

**Comment by pdjohntony** [comment]
> 

How did you fix this?

**Comment by pdjohntony** [comment]
> There is no such file. 404 Client Error: Entry Not Found for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/main/config.json
> 
> Edit: Issue resolved.

@Daniel-Kelvich  How did you fix this?

**Comment by ShivamShrirao** [comment]
@pdjohntony What error are you facing ? If 404, it may be due to not being authenticated with huggingface cli.

**Comment by pdjohntony** [comment]
@ShivamShrirao I managed to get your dreambooth example working but its been running for 2 hours now on an A5000.

Since thats taking so long, I spun up another instance on vast with 2 A5000's but now I'm getting the 404. It shouldn't be an auth issue with huggingface as a logged in on the CLI and it appeared to download the model for a while before getting this 404 error.

```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `24` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/transformers/configuration_utils.py", line 596, in _get_config_dict
    resolved_config_file = cached_path(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/transformers/utils/hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/transformers/utils/hub.py", line 486, in get_from_cache
    _raise_for_status(r)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in _raise_for_status
    raise EntryNotFoundError(f"404 Client Error: Entry Not Found for url: {request.url}")
transformers.utils.hub.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/main/config.json
```

**Comment by roar-emaus** [comment]
Great work! I managed to run it in a google colab. I was just wondering, how do I get checkpoint files that I can use later on from the model files that are stored?

I could only find the
`feature_extractor  logs  model_index.json  safety_checker  scheduler  text_encoder  tokenizer  unet  vae` folders/files that were stored in the `--output_dir=$OUTPUT_DIR` after it was done training.

**Comment by ShivamShrirao** [comment]
@roar-emaus  These are the diffuser version of weights. I have added an inference example in colab on how to use them in diffusers. For others you will need to convert them.

**Comment by roar-emaus** [comment]
> @roar-emaus  These are the diffuser version of weights. I have added an inference example in colab on how to use them in diffusers. For others you will need to convert them.

Thank you! will test it tomorrow :)

**Comment by Ai-Artsca** [comment]
finally got it to work, how can we use the model to reuse in a stable colab @ShivamShrirao ? I have used the inference but how do i save my model, i havent even been able to find what folder its in lol, any info on how to convert it into a ckpt?? great work !!

**Comment by ShivamShrirao** [comment]
> finally got it to work, how can we use the model to reuse in a stable colab @ShivamShrirao ? I have used the inference but how do i save my model, i havent even been able to find what folder its in lol, any info on how to convert it into a ckpt?? great work !!

I haven't figured out yet how to convert to single ckpt to use in other repos. Currently the whole folder is your model, you can save the whole folder until someone figures it out. This needs to be reversed https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by hopibel** [comment]
@ShivamShrirao If I'm reading things right, 8bit AdamW should be a drop in replacement and the modified CrossAttention class seems like it should just be able to replace the one in ldm/modules/attention.py in this repository. Sadly can't test it myself because bitsandbytes has a C extension that uses CUDA and I'm on AMD

**Comment by guumaster** [comment]
@ShivamShrirao is there any way to convert the model folder to a portable checkpoint file that can be used with a WebUI?

**Comment by Ai-Artsca** [comment]
successfully trained one model, but my second time training im getting an error @ShivamShrirao 

Steps:   2% 18/1000 [00:56<45:45,  2.80s/it, loss=0.536, lr=5e-6]Traceback (most recent call last):
  File "train_dreambooth.py", line 606, in <module>
    main()
  File "train_dreambooth.py", line 527, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_dreambooth.py", line 268, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/data/sks/.ipynb_checkpoints'
Steps:   2% 18/1000 [00:56<51:30,  3.15s/it, loss=0.536, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/sks', '--class_data_dir=/content/data/gfx', '--output_dir=/content/models/sks', '--with_prior_preservation', '--instance_prompt=photo of sks gfx', '--class_prompt=photo of a gfx', '--resolution=512', '--use_8bit_adam', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=1000']' returned non-zero exit status 1.

**Comment by TemporalLabsLLC-SOL** [comment]
Very nice progress! Digging in more now

**Comment by Daniel-Kelvich** [comment]
@pdjohntony try to update transformers library `pip install -U transformers`

**Comment by ClashSAN** [comment]
@ShivamShrirao I'm assuming you mean only the items in the imv folder make up the ckpt file, I deleted my colab and only saved those items to the google drive

**Comment by binarymind** [comment]
@ShivamShrirao 

in the collab 
```
  --instance_prompt="photo of imv{CLASS_NAME}" \
  --class_prompt="photo of a {CLASS_NAME}" \
```
are no f strings, they should be right ?

cheers

**Comment by ShivamShrirao** [comment]
@binarymind Not required here cause it executes as a shell command.

**Comment by binarymind** [comment]
ok thanks !

during this cell I got the following result
```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `32` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py:179: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Fetching 16 files: 100%|█████████████████████| 16/16 [00:00<00:00, 13678.94it/s]
Generating class images:   0%|                           | 0/25 [00:00<?, ?it/s]FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
```

my nvidia-smi is the following
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.94       Driver Version: 470.94       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:0F:00.0 Off |                  Off |
| 30%   27C    P8    26W / 300W |      1MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I tried also to do the 

`%pip install git+https://github.com/facebookresearch/xformers@1d31a3a#egg=xformers` some cells above as it was not working.
currently stucked there

**Comment by binarymind** [comment]
@ShivamShrirao (pinging cause I edited the comment). If you have no idea of the issue, its allright. thanks for the work anyway

**Comment by binarymind** [comment]
Lol I fixed my problem by removing the f strings I added.... sorry

edit: ah nope was not that, launched again the notebook on a new repo and the problem appear again, looking at it

**Comment by TheChapster** [comment]
I'm hoping for a (fingers crossed not too distant) future version of this that can run on requirements of a 3080. Will put it into reach of many more people including myself. Keep up the great work!!

**Comment by JoeMcGuire** [comment]
I'm not having any success. Trying to use V100 on colab.

```
Generating class images:   0% 0/50 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "train_dreambooth.py", line 606, in <module>
    main()
  File "train_dreambooth.py", line 362, in main
    images = pipeline(example["prompt"]).images
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 259, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_condition.py", line 254, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 565, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 155, in forward
    hidden_states = block(hidden_states, context=context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 204, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 288, in forward
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value)
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 575, in memory_efficient_attention
    query=query, key=key, value=value, attn_bias=attn_bias, p=p
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 196, in forward_no_grad
    causal=isinstance(attn_bias, LowerTriangularMask),
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/sks', '--class_data_dir=/content/data/dog', '--output_dir=/content/models/sks', '--with_prior_preservation', '--instance_prompt=photo of sks dog', '--class_prompt=photo of a dog', '--resolution=512', '--use_8bit_adam', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=600']' returned non-zero exit status 1
```

**Comment by ShivamShrirao** [comment]
@JoeMcGuire you will need to compile the xformers, current wheels only support T4 GPU.

**Comment by 1blackbar** [comment]
there are xformers for p100 on this colab precompiled, how to incorporate those into dreambooth ? It will cover colab pro
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=a---cT2rwUQj

under installing xformers 
Also how about optional googledrive cell to upload trained model + prune cell to get it to 2gb?
If some of You will compile whl for p100 please download and store it in gdrive to share

**Comment by AmericanPresidentJimmyCarter** [comment]
> > finally got it to work, how can we use the model to reuse in a stable colab @ShivamShrirao ? I have used the inference but how do i save my model, i havent even been able to find what folder its in lol, any info on how to convert it into a ckpt?? great work !!
> 
> I haven't figured out yet how to convert to single ckpt to use in other repos. Currently the whole folder is your model, you can save the whole folder until someone figures it out. This needs to be reversed https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

https://github.com/harubaru/waifu-diffusion/blob/main/scripts/convert-diffusers.py

**Comment by 1blackbar** [comment]
yeah , now its kinda not useable on webuis and most people are on webuis, huggingface love their bins also default 600 steps are pretty bad, not sure why its default ? should be more like at least 2000

**Comment by Blucknote** [comment]
Any chances to run on 12GB rtx 3060?
I'm getting `Tried to allocate 4.00 GiB (GPU 0; 12.00 GiB total capacity; 4.81 GiB already allocated; 890.00 MiB free; 8.81 GiB reserved in total by PyTorch)` error even with `--use_8bit_adam` flag

**Comment by ShivamShrirao** [comment]
@Blucknote hopefully pretty soon. I have gotten the GPU usage just under 12 GB, but there are a few bugs due to which the model output quality isn't good right now even for higher precision. Will update once quality gets better.
![Screenshot_20220929_014104](https://user-images.githubusercontent.com/37087513/192879106-4c277356-0294-425a-8e8f-136bb98a8c98.png)

**Comment by ShivamShrirao** [comment]
@Blucknote hopefully pretty soon. I have gotten the GPU usage to 11.187 GB, but there are a few bugs due to which the model output quality isn't good right now even for higher precision. Will update once quality gets better.
![Screenshot_20220929_014712](https://user-images.githubusercontent.com/37087513/192880168-2b27a74d-ffa9-42f3-8ff5-28c251c41805.png)

**Comment by TemporalLabsLLC-SOL** [comment]
Can we get a link to the json or description on that?

**Comment by UrbanLegendXV** [comment]
![jsonerror](https://user-images.githubusercontent.com/47697347/192884433-b6038716-6fa3-4cfe-a6c2-5dbf883aa539.png)

**Comment by UrbanLegendXV** [comment]
Current Issue 

The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `4` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "train_dreambooth.py", line 606, in <module>
    main()
  File "train_dreambooth.py", line 396, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\transformers\tokenization_utils_base.py", line 1764, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/stable-diffusion-v1-4' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "c:\users\urban\anaconda3\envs\ldm\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\urban\anaconda3\envs\ldm\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Urban\anaconda3\envs\ldm\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 837, in launch_command
    simple_launcher(args)
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by TemporalLabsLLC-SOL** [comment]
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `4` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "train_dreambooth.py", line 608, in <module>
    main()
  File "train_dreambooth.py", line 394, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\transformers\tokenization_utils_base.py", line 1764, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/CompVis/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/CompVis/stable-diffusion-v1-4' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "c:\users\urban\anaconda3\envs\ldm\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\urban\anaconda3\envs\ldm\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Urban\anaconda3\envs\ldm\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 837, in launch_command
    simple_launcher(args)
  File "c:\users\urban\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)


SOLVE = pip install --upgrade transformers

**Comment by TemporalLabsLLC-SOL** [comment]
I've tried both local directories matching and making sure there are zero that match. So close. Would appreciate any help anybody has to offer.

**Comment by UrbanLegendXV** [comment]
# Load the tokenizer
    if args.tokenizer_name:
        tokenizer = CLIPTokenizer.from_pretrained(args.tokenizer_name)
    elif args.pretrained_model_name_or_path:
        tokenizer = CLIPTokenizer.from_pretrained(
            args.pretrained_model_name_or_path, subfolder="tokenizer", use_auth_token=args.use_auth_token
        )

    # Load models and create wrapper for stable diffusion
    text_encoder = CLIPTextModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="text_encoder", use_auth_token=args.use_auth_token
    )
    vae = AutoencoderKL.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="vae", use_auth_token=args.use_auth_token
    )
    unet = UNet2DConditionModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="unet", use_auth_token=args.use_auth_token
    )

**Comment by UrbanLegendXV** [comment]
# Use 8-bit Adam for lower memory usage or to fine-tune the model in 16GB GPUs
    if args.use_8bit_adam:
        try:
            import bitsandbytes as bnb
        except ImportError:
            raise ImportError(
                "To use 8-bit Adam, please install the bitsandbytes library: `pip install bitsandbytes`."
            )


This is giving me this error

**Comment by konimaki2022** [comment]
Hello, i have trained on an RTX 2060 with a stable consumption of 10.8GB of VRAM and at an amazing speed, between 5 and 10 minutes!

These are the details of my configuration:

- torch and torchvision compiled with support for cuda 11.6
- accelerate configured to use --mixed_precision with bf16
- reduced size of training images with --resolution=256
- with 3-5 images for instance, and 12-20 images for class, 1000 training steps.

I obtain very good results.

**Comment by guumaster** [comment]
@konimaki2022 can you share your notebook?

**Comment by konimaki2022** [comment]
@guumaster sorry I haven't created a notebook in Google Colab yet, I run it on my local computer with Ubuntu 20.04, no cloud.

**Comment by TemporalLabsLLC-SOL** [comment]
> @guumaster sorry I haven't created a notebook in Google Colab yet, I run it on my local computer with Ubuntu 20.04, no cloud.

I think Ubuntu is the key. Because we have to redirect Cuda drivers to invoke adam right in windows it's cause two straight days of work. Close hopefully

**Comment by TemporalLabsLLC-SOL** [comment]
I've learned a lot and I think a more stable and universal windows local solution is close.

**Comment by ShivamShrirao** [comment]
https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth

New version now trains in 10 GB.
![Screenshot_20221002_032336](https://user-images.githubusercontent.com/37087513/193457886-87b03db8-d326-41b6-a1c2-11fa8585e2c5.png)

**Comment by TheChapster** [comment]
> https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth
> 
> New version now trains in 10 GB.

Awesome!! I assume this wont work with a 10GB GPU still, due to other apps using it. If anyone knows of a way to get it working with that, such as utilising shared memory (not worrying about a decrease in performance), that would be fantastic!! If not, I look forward to future progressions!

**Comment by ShivamShrirao** [comment]
@TheChapster It might work on linux where you can have no other application running on the GPU, or might need just a few modifications. I don't have a 10GB GPU to test it so can't confirm.

**Comment by hopibel** [comment]
> https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth
> 
> New version now trains in 10 GB.

Can we get a row or two in the table with all optimizations on except for `use_8bit_adam`? The bitsandbytes library relies on a C extension to wrap some CUDA functions, so it can't be used on AMD

**Comment by ShivamShrirao** [comment]
@hopibel Check the last row.

**Comment by hopibel** [comment]
Ah, missed it somehow. Dang, looks too close to 16GB to fit

**Comment by AmericanPresidentJimmyCarter** [comment]
With `xformers` and `triton` in this my fork at FP16 it trains with slightly less than 14 GB... I haven't pushed the branch but it seems fine.

This is using `stable-diffusion` and EMA weights, not `diffusers` at all.

**Comment by ShivamShrirao** [comment]
Now you can convert diffusers weights to ckpt, thanks to https://gist.github.com/jachiam/8a5c0b607e38fcc585168b90c686eb05

I have updated it in my colab.

**Comment by andreae293** [comment]
> With `xformers` and `triton` in this my fork at FP16 it trains with slightly less than 14 GB... I haven't pushed the branch but it seems fine.
> 
> This is using `stable-diffusion` and EMA weights, not `diffusers` at all.



> 

can you push it? thanks

**Comment by Jarfeh** [comment]
> With `xformers` and `triton` in this my fork at FP16 it trains with slightly less than 14 GB... I haven't pushed the branch but it seems fine.
> 
> This is using `stable-diffusion` and EMA weights, not `diffusers` at all.

Like andrae293, I too would like to see you push this to be available :)

**Comment by feffy380** [comment]
@Jarfeh This repo seems abandoned. Use [ShivamShrirao's diffusers fork](https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth) instead. It includes all the optimizations discussed here and some new ones

**Comment by titusfx** [comment]
@Jarfeh I agree with @feffy380

https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth

**Comment by Hbhatt-merexgenAI** [comment]
I tried to run the Google Colab, I have RTX 3060 12Gb but doesnt work

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.25 GiB (GPU 0; 11.75 GiB total capacity; 8.06 GiB already allocated; 1.95 GiB free; 8.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7772) of binary: /home/merexai-dev/miniconda3/envs/tf/bin/python
Traceback (most recent call last):
