### ISSUE TITLE
Loading model in Super Stable

### ISSUE THREAD

**Issue by Ai-Artsca** [XavierXiao/Dreambooth-Stable-Diffusion#43]
To create a public link, set `share=True` in `launch()`.
Loading weights [6f849715] from C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\models\gfx_20_training_images_2020_batch_size_person_class_word.ckpt
Traceback (most recent call last):
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 742, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 653, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\modules\ui.py", line 927, in run_settings
    opts.data_labels[key].onchange()
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\webui.py", line 41, in f
    res = func(*args, **kwargs)
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\webui.py", line 73, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights(shared.sd_model)))
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\modules\sd_models.py", line 147, in reload_model_weights
    load_model_weights(sd_model, checkpoint_info.filename, checkpoint_info.hash)
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\modules\sd_models.py", line 97, in load_model_weights
    pl_sd = torch.load(checkpoint_file, map_location="cpu")
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Python_Scripts\_stableDiffusion\super-stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by wangrui6** [comment]
any update on this?  Got the same error 

Global seed set to 42
Loading model from ./sd_ckpts/sd-v1-4-full-ema.ckpt
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 292, in <module>
    main()
  File "scripts/stable_txt2img.py", line 195, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/stable_txt2img.py", line 27, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/home/rwna/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/rwna/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
