### ISSUE TITLE
Getting a strange trainer and key reg error

### ISSUE THREAD

**Issue by jordanthomp81** [XavierXiao/Dreambooth-Stable-Diffusion#44]
This is what I get when trying to run the training command
Traceback (most recent call last):
  File "main.py", line 634, in <module>
    config.data.params.reg.params.placeholder_token = opt.class_word
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key reg
    full_key: data.params.reg
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 851, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

Also as a side question, I haven't been sure what exactly is the difference between the data_root images and the reg_data_root images in the training command?

**Comment by medcelerate** [comment]
How did you solve this
?

**Comment by jordanthomp81** [comment]
Actually didn't. Prematurely closed the issue. I was using the regular fine tune file instead of the frozen and figured that was my problem, but upon testing that's not the case. Wish I could reopen issue.

**Comment by jordanthomp81** [comment]
I reload ldm and now am just getting this
Traceback (most recent call last):
File "main.py", line 609, in <module>
  configs = [OmegaConf.load(cfg) for cfg in opt.base]
File "main.py", line 609, in <listcomp>
  configs = [OmegaConf.load(cfg) for cfg in opt.base]
File "/home/linuxinstall/anaconda3/envs/ldm/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 183, in load
  with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/linuxinstall/Desktop/dream/Dreambooth-SD-optimized/configs/stable-diffusion/v1-finetune-test.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 858, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by jordanthomp81** [comment]
Reinstalled ldm dependencies, and swapped to the frozen finetune file as examples show. One of these seemed to make it work
