### ISSUE TITLE
Crashing when saving checkpoint to file

### ISSUE THREAD

**Issue by TrophiHunter** [XavierXiao/Dreambooth-Stable-Diffusion#45]
Every time I train a model it crashes when saving the checkpoint

`Epoch 0, global step 499: val/loss_simple_ema was not in top 1
Summoning checkpoint.

Traceback (most recent call last):
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 499, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 380, in save
    return
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:300] . unexpected pos 6057217600 vs 6057217496

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 836, in <module>
    trainer.fit(model, data)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 216, in advance
    self.trainer.call_hook("on_train_batch_end", batch_end_outputs, batch, batch_idx, **extra_kwargs)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 181, in on_train_batch_end
    callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 309, in on_train_batch_end
    self.save_checkpoint(trainer)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 400, in save_checkpoint
    self._save_last_checkpoint(trainer, monitor_candidates)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 670, in _save_last_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1913, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 472, in save_checkpoint
    self.trainer.training_type_plugin.save_checkpoint(_checkpoint, filepath)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 294, in save_checkpoint
    return self.checkpoint_io.save_checkpoint(checkpoint, filepath)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\plugins\io\torch_plugin.py", line 37, in save_checkpoint
    atomic_save(checkpoint, path)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\utilities\cloud_io.py", line 68, in atomic_save
    torch.save(checkpoint, bytesbuffer)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 381, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 225, in __exit__
    self.file_like.flush()
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 499, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 380, in save
    return
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:300] . unexpected pos 9857564736 vs 9857564632

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 838, in <module>
    melk()
  File "main.py", line 818, in melk
    trainer.save_checkpoint(ckpt_path)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1913, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 472, in save_checkpoint
    self.trainer.training_type_plugin.save_checkpoint(_checkpoint, filepath)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 294, in save_checkpoint
    return self.checkpoint_io.save_checkpoint(checkpoint, filepath)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\plugins\io\torch_plugin.py", line 37, in save_checkpoint
    atomic_save(checkpoint, path)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\pytorch_lightning\utilities\cloud_io.py", line 68, in atomic_save
    torch.save(checkpoint, bytesbuffer)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 381, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "H:\Anaconda\envs\dreambooth\lib\site-packages\torch\serialization.py", line 225, in __exit__
    self.file_like.flush()
ValueError: I/O operation on closed file.`

**Comment by TrophiHunter** [comment]
You really can't have any other program open, worked with 0.6gb usage (3090)
