### ISSUE TITLE
NameError: name 'trainer' is not defined

### ISSUE THREAD

**Issue by ffdown** [XavierXiao/Dreambooth-Stable-Diffusion#47]
Traceback (most recent call last):
  File "E:\ai\sd\dbsdo\main.py", line 643, in <module>
    model = load_model_from_config(config, opt.actual_resume)
  File "E:\ai\sd\dbsdo\main.py", line 30, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "E:\ai\sd\dbsdo\ldm\util.py", line 86, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "E:\ai\sd\dbsdo\ldm\util.py", line 94, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "E:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\ai\sd\dbsdo\ldm\models\diffusion\ddpm.py", line 26, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "E:\ai\sd\dbsdo\ldm\models\autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (E:\Anaconda3\lib\site-packages\taming\modules\vqvae\quantize.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ai\sd\dbsdo\main.py", line 860, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by MaxisAI** [comment]
what's the code that gave you this error

**Comment by Fealix13** [comment]
I get this error after running the step after "Edit the personalized.py file" specifically #START THE TRAINING 

Traceback (most recent call last):
  File "C:\Users\Fealix\stable-diffusion-webui\dreambooth\Dreambooth-Stable-Diffusion\main.py", line 869, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

The codeblock that contains this line in the traceback reads as follows

# move newly created debug project to debug_runs
        if opt.debug and not opt.resume and trainer.global_rank == 0:
            dst, name = os.path.split(logdir)
            dst = os.path.join(dst, "debug_runs", name)
            os.makedirs(os.path.split(dst)[0], exist_ok=True)
            os.rename(logdir, dst)
        if trainer.global_rank == 0:    <---------- This is line 869 in my main.py
            print("Training complete. max_training_steps reached or we blew up.")
            # print(trainer.profiler.summary())
            
This is an issue that is not isolated to my installation either. Aitrepreneur mentions it in his video on Youtube ( https://www.youtube.com/watch?v=TgUrA1Nq4uE ) at timestamp 4:27 ish.

Please let me know if I can assist further with more information. I am going to reinstall but keep my old install around for the purposes of troubleshooting this error.

**Comment by manugarri** [comment]
same error here. Running the training step 
```
python main.py --base configs/stable-diffusion/v1-finetune_unfrozen.yaml 
                -t 
                --actual_resume /path/to/original/stable-diffusion/sd-v1-4-full-ema.ckpt  
                -n <job name> 
                --gpus 0, 
                --data_root /root/to/training/images 
                --reg_data_root /root/to/regularization/images 
                --class_word <xxx>
```
![image](https://user-images.githubusercontent.com/3670355/193539316-6a3ecd71-898e-4eb3-b139-085b65572f01.png)

 I think the issue is the main.py is wrapped in a massive try catch and if there is an exception before defining the `trainer` instance, well, it just explodes with a non descriptive error.

In my case, the TestTubeLogger setup by default in this repo config is not supported anymore by [pytorch lighting](https://github.com/Lightning-AI/lightning/issues/13958).

Changing [this line](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/blob/main/main.py#L657) and [this line](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/blob/main/main.py#L371) to `CSVLogger`

**UPDATE** just do yourself a favor and install a fairly old version of pytorch lighting 1.5.9, it will fix this issue and other ones you will see.

**Comment by Tjplump** [comment]
I am having this exact same error code, however installing the older version of pytorch-lightning hasn't fixed the issue. any other ideas would be much appreciated!!

**Comment by davidmcw289** [comment]
Deleting the Conda Enviroment, reinstalling SD, and copying(replacing some 70ish files) the dreambooth repo into the SD one fixed it for me.

**Comment by MesutUnutur** [comment]
@davidmcw289 hi. I have same ıssue. How could you solve this? Can you tell it more detail, please. I dont understand now. Thank you
