### ISSUE TITLE
Missing parentheses when running stable_txt2img.py

### ISSUE THREAD

**Issue by danielraffel** [XavierXiao/Dreambooth-Stable-Diffusion#82]
when I run the following on a Mac M1
`% python scripts/stable_txt2img.py --ddim_eta 0.0 --n_samples 8 --n_iter 1 --scale 10.0 --ddim_steps 50  --ckpt /path/to/original/stable-diffusion/sd-v1-4-full-ema.ckpt --prompt "a photo of a dog"`

I get the following errors, any suggestions?
```
WARNING:root:Pytorch pre-release version 1.13.0.dev20220922 - assuming intent to test it
Traceback (most recent call last):
  File "/Users/somehuman/Dreambooth-Stable-Diffusion/scripts/stable_txt2img.py", line 15, in <module>
    from ldm.util import instantiate_from_config
  File "/Users/somehuman/miniforge3/lib/python3.10/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by ariand9** [comment]
Im getting the same error on MacOS.

**Comment by longlimin** [comment]
I have same probleme, my solution: do not install ldm, and  use  the project ldm code. add file xx.pth,  include "xxx/xx/Dreambooth-Stable-Diffusion"
