### ISSUE TITLE
ModuleNotFoundError: No module named 'taming'

### ISSUE THREAD

**Issue by chuiliuyiyi** [XavierXiao/Dreambooth-Stable-Diffusion#90]
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 294, in <module>
    main()
  File "scripts/stable_txt2img.py", line 197, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/stable_txt2img.py", line 33, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "D:\Program Files\python3.8.3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddpm.py", line 26, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'

**Comment by bhavinjawade** [comment]
You will need to install `taming-transformers`:
```
pip install taming-transformers-rom1504
```

**Comment by Walterkd** [comment]
> 

Thanks! Solved my problem.

**Comment by jinmingShanDong** [comment]
Thanks! Solved the problem.
