### ISSUE TITLE
RuntimeError: expected scalar type BFloat16 but found Float

### ISSUE THREAD

**Issue by chuiliuyiyi** [XavierXiao/Dreambooth-Stable-Diffusion#91]
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 294, in <module>
    main()
  File "scripts/stable_txt2img.py", line 248, in main
    samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddim.py", line 95, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddim.py", line 148, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddim.py", line 176, in p_sample_ddim
    e_t_uncond, e_t = self.model.apply_model(x_in.to(dtype = torch.bfloat16), t_in.to(dtype = torch.bfloat16), c_in.to(dtype = torch.bfloat16)).chunk(2)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddpm.py", line 1050, in apply_model
    x_recon = self.model(x_noisy.to(dtype = torch.bfloat16), t, **cond)
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\models\diffusion\ddpm.py", line 1536, in forward
    out = self.diffusion_model(x.to(dtype = torch.bfloat16), t.to(dtype = torch.bfloat16), context=cc)
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\modules\diffusionmodules\openaimodel.py", line 733, in forward
    h = module(h.to(dtype = th.bfloat16), emb.to(dtype = th.bfloat16), context.to(dtype = th.bfloat16))
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\modules\diffusionmodules\openaimodel.py", line 86, in forward
    x = layer(x, context)
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\ldm\modules\attention.py", line 255, in forward
    x = self.norm(x)
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward
    return F.group_norm(
  File "D:\Program Files\python3.8.3\lib\site-packages\torch\nn\functional.py", line 2528, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type BFloat16 but found Float

**Comment by thupx** [comment]
Same error. Any solution? Adding '--precision full' is not helpful.

**Comment by pauliustumas** [comment]
For me helped --device cuda

**Comment by thupx** [comment]
> For me helped --device cuda

Thanks, I've solved that too. 
It's rather strange that the default value of `--device` is set to be `CPU`...
