### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'personalization_config'

### ISSUE THREAD

**Issue by Bingyan-Liu** [XavierXiao/Dreambooth-Stable-Diffusion#92]
how can I solve this problem when I create images for regularization? 
python scripts/stable_txt2img.py --ddim_eta 0.0 --n_samples 8 --n_iter 1 --scale 10.0 --ddim_steps 50  --ckpt pretrained_model/sd-v1-4-full-ema.ckpt --prompt "a photo of a <cat>" 
Global seed set to 42
Loading model from pretrained_model/sd-v1-4-full-ema.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "scripts/stable_txt2img.py", line 292, in <module>
    main()
  File "scripts/stable_txt2img.py", line 195, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/stable_txt2img.py", line 31, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/mnt/nas/zhuxiangru.zxr/workspace/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/mnt/nas/zhuxiangru.zxr/workspace/stable-diffusion/ldm/models/diffusion/ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'personalization_config'

**Comment by Bingyan-Liu** [comment]
re-use pip install -e . work for me.

**Comment by tanshuai0219** [comment]
> re-use pip install -e . work for me.

Thanks, it works for me, too.
